@ cdecl PassThruOpen(ptr ptr)
@ cdecl PassThruClose(long)
@ cdecl PassThruConnect(long long long long ptr)
@ cdecl PassThruDisconnect(long)
@ cdecl PassThruReadMsgs(long ptr ptr long)
@ cdecl PassThruWriteMsgs(long ptr ptr long)
@ cdecl PassThruStartPeriodicMsg(long ptr ptr long)
@ cdecl PassThruStopPeriodicMsg(long long)
@ cdecl PassThruStartMsgFilter(long long ptr ptr ptr ptr)
@ cdecl PassThruStopMsgFilter(long long)
@ cdecl PassThruSetProgrammingVoltage(long long long)
@ cdecl PassThruReadVersion(long ptr ptr ptr)
@ cdecl PassThruGetLastError(ptr)
@ cdecl PassThruIoctl(long long ptr ptr)
